export default (s:string, space:string = " ") => {
    if (typeof s !== 'string') return
    return s.replace(/а/gi, 'a')
                 .replace(/б/gi, 'b')
                 .replace(/в/gi, 'v')
                 .replace(/г/gi, 'g')
                 .replace(/д/gi, 'd')
                 .replace(/е/gi, 'e')
                 .replace(/ё/gi, 'e')
                 .replace(/ж/gi, 'zh') 
                 .replace(/з/gi, 'z')
                 .replace(/и/gi, 'i')
                 .replace(/й/gi, 'y')
                 .replace(/к/gi, 'k')
                 .replace(/л/gi, 'l')
                 .replace(/м/gi, 'm')
                 .replace(/н/gi, 'n')
                 .replace(/о/gi, 'o')
                 .replace(/п/gi, 'p')
                 .replace(/р/gi, 'r')
                 .replace(/с/gi, 's')
                 .replace(/т/gi, 't')
                 .replace(/у/gi, 'u')
                 .replace(/ф/gi, 'f')
                 .replace(/х/gi, 'h')
                 .replace(/ц/gi, 'ts')
                 .replace(/ч/gi, 'ch') 
                 .replace(/ш/gi, 'sh') 
                 .replace(/щ/gi, 'shh')
                 .replace(/ы/gi, 'yi')
                 .replace(/ь/gi, '')
                 .replace(/э/gi, 'e')
                 .replace(/ю/gi, 'yu')
                 .replace(/я/gi, 'ya')
                 .replace(/\./g, '')
                 .replace(/\s/g, space)
                 .toLowerCase()
}

